// Generated by gencpp from file multi_msgs/multi_images.msg
// DO NOT EDIT!


#ifndef MULTI_MSGS_MESSAGE_MULTI_IMAGES_H
#define MULTI_MSGS_MESSAGE_MULTI_IMAGES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <sensor_msgs/Image.h>

namespace multi_msgs
{
template <class ContainerAllocator>
struct multi_images_
{
  typedef multi_images_<ContainerAllocator> Type;

  multi_images_()
    : header()
    , nimgs(0)
    , imgs()  {
    }
  multi_images_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , nimgs(0)
    , imgs(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _nimgs_type;
  _nimgs_type nimgs;

   typedef std::vector< ::sensor_msgs::Image_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::sensor_msgs::Image_<ContainerAllocator> >::other >  _imgs_type;
  _imgs_type imgs;





  typedef boost::shared_ptr< ::multi_msgs::multi_images_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::multi_msgs::multi_images_<ContainerAllocator> const> ConstPtr;

}; // struct multi_images_

typedef ::multi_msgs::multi_images_<std::allocator<void> > multi_images;

typedef boost::shared_ptr< ::multi_msgs::multi_images > multi_imagesPtr;
typedef boost::shared_ptr< ::multi_msgs::multi_images const> multi_imagesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::multi_msgs::multi_images_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::multi_msgs::multi_images_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::multi_msgs::multi_images_<ContainerAllocator1> & lhs, const ::multi_msgs::multi_images_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.nimgs == rhs.nimgs &&
    lhs.imgs == rhs.imgs;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::multi_msgs::multi_images_<ContainerAllocator1> & lhs, const ::multi_msgs::multi_images_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace multi_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::multi_msgs::multi_images_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::multi_msgs::multi_images_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::multi_msgs::multi_images_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::multi_msgs::multi_images_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::multi_msgs::multi_images_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::multi_msgs::multi_images_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::multi_msgs::multi_images_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0b5e6704d1ef14a398cbd54f53d1bc7d";
  }

  static const char* value(const ::multi_msgs::multi_images_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0b5e6704d1ef14a3ULL;
  static const uint64_t static_value2 = 0x98cbd54f53d1bc7dULL;
};

template<class ContainerAllocator>
struct DataType< ::multi_msgs::multi_images_<ContainerAllocator> >
{
  static const char* value()
  {
    return "multi_msgs/multi_images";
  }

  static const char* value(const ::multi_msgs::multi_images_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::multi_msgs::multi_images_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"int32 nimgs\n"
"sensor_msgs/Image[] imgs\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/Image\n"
"# This message contains an uncompressed image\n"
"# (0, 0) is at top-left corner of image\n"
"#\n"
"\n"
"Header header        # Header timestamp should be acquisition time of image\n"
"                     # Header frame_id should be optical frame of camera\n"
"                     # origin of frame should be optical center of camera\n"
"                     # +x should point to the right in the image\n"
"                     # +y should point down in the image\n"
"                     # +z should point into to plane of the image\n"
"                     # If the frame_id here and the frame_id of the CameraInfo\n"
"                     # message associated with the image conflict\n"
"                     # the behavior is undefined\n"
"\n"
"uint32 height         # image height, that is, number of rows\n"
"uint32 width          # image width, that is, number of columns\n"
"\n"
"# The legal values for encoding are in file src/image_encodings.cpp\n"
"# If you want to standardize a new string format, join\n"
"# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n"
"\n"
"string encoding       # Encoding of pixels -- channel meaning, ordering, size\n"
"                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n"
"\n"
"uint8 is_bigendian    # is this data bigendian?\n"
"uint32 step           # Full row length in bytes\n"
"uint8[] data          # actual matrix data, size is (step * rows)\n"
;
  }

  static const char* value(const ::multi_msgs::multi_images_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::multi_msgs::multi_images_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.nimgs);
      stream.next(m.imgs);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct multi_images_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::multi_msgs::multi_images_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::multi_msgs::multi_images_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "nimgs: ";
    Printer<int32_t>::stream(s, indent + "  ", v.nimgs);
    s << indent << "imgs[]" << std::endl;
    for (size_t i = 0; i < v.imgs.size(); ++i)
    {
      s << indent << "  imgs[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "    ", v.imgs[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MULTI_MSGS_MESSAGE_MULTI_IMAGES_H
